name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            ui/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 对应你本地的：cd ui && npm install
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ui

      # 对应你本地最终执行 npm run tauri build
      # Tauri CLI 在根目录，所以必须安装根目录依赖
      - name: Install root dependencies
        run: npm ci

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}

          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'DotWallpaper ${{ github.ref_name }}'

          releaseBody: |
            ### ✨ 新增
            - 新增跳转到当前文件目录
            - 新增收藏页面
            - 新增快捷键收藏Ctrl+F
            - 新增壁纸源设置
  
            ### 🐛 修复
            - 少量图片会直接占满整个高度
            
            ### 🎨 优化 
            - 优化设为壁纸

          releaseDraft: false
          prerelease: false

          # 你的 Tauri 项目在根目录，不是 ui
          projectPath: .